export const FETCH_PRODUCTS_INITIATED = "fetch_products_initiated"
export const FETCH_PRODUCTS_SUCCESS = "fetch_products_success"
export const FETCH_PRODUCTS_FAILURE = "fetch_products_failure"
export const ADD_TO_CART = "add_to_cart"
export const REMOVE_FROM_CART = "remove_from_cart"
export const CHANGEMODE = "day_night_mode"